# Generated by Django 6.0.3 on 2026-03-31 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название тура')),
                ('description', models.TextField(verbose_name='Описание тура')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('duration', models.IntegerField(verbose_name='Длительность (дней)')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('people', models.IntegerField(verbose_name='Количество людей')),
                ('tour_date', models.DateField(verbose_name='Дата тура')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.tour')),
            ],
        ),
        migrations.CreateModel(
            name='TourImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tours/', verbose_name='Фотография тура')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.tour')),
            ],
        ),
    ]
