# Generated by Django 6.0.3 on 2026-05-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tourschedule',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='tourschedule',
            constraint=models.UniqueConstraint(fields=('tour', 'start_date'), name='unique_tour_start_date'),
        ),
    ]
