# Generated by Django 6.0.3 on 2026-04-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='removed',
            field=models.BooleanField(default=False),
        ),
    ]
