# Generated by Django 6.0.3 on 2026-03-31 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='max_people',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='booking',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='people',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tour_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tour',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tour',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='TourMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tours/')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.tour')),
            ],
        ),
        migrations.DeleteModel(
            name='TourImage',
        ),
    ]
