# Generated by Django 6.0.3 on 2026-04-01 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_tour_image_alter_booking_name_alter_tour_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='image',
            field=models.ImageField(default='tours/default.jpg', upload_to='tours/'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
